org.gradle.jvmargs=-Xms512M -Xmx6G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=richstuff
mod_name=Rich Stuff
mod_license=All Rights Reserved
mod_version=0.0.17
mod_group_id=com.richetoku.richstuff
