[mob_chamber]
	# Default: 600
	# Range: 1 ~ 72000
	cycleTicks = 600
	# Default: 16
	# Range: 1 ~ 16384
	minimumMobRpmCost = 16
	# Default: 4096
	# Range: 1 ~ 65536
	maximumMobRpmCost = 4096
	#FE consumed per 1 RPM-equivalent per second.
	# Default: 4
	# Range: 1 ~ 4096
	fePerRpm = 4
	# Default: 27
	# Range: 1 ~ 27
	maximumSimultaneouslyProcessedMobs = 27
	# Default: 1.0
	# Range: 0.0 ~ 100.0
	healthMultiplier = 1.0
	# Default: 3.0
	# Range: 0.0 ~ 100.0
	armorMultiplier = 3.0
	# Default: 5.0
	# Range: 0.0 ~ 100.0
	attackMultiplier = 5.0
	# Default: 8.0
	# Range: 0.0 ~ 100.0
	sizeMultiplier = 8.0
	# Default: 1.35
	# Range: 0.0 ~ 100.0
	hostileMobMultiplier = 1.35
	# Default: 8.0
	# Range: 0.0 ~ 100.0
	bossMobMultiplier = 8.0
	# Default: 1.35
	# Range: 0.0 ~ 100.0
	flyingMobMultiplier = 1.35
	# Default: 1.4
	# Range: 0.0 ~ 100.0
	rangedMobMultiplier = 1.4
	# Default: 1.3
	# Range: 0.0 ~ 100.0
	specialAbilityMultiplier = 1.3
	# Default: 1.0
	# Range: 0.0 ~ 100.0
	dropValueMultiplier = 1.0
	allowMultipleIdenticalMobs = true
	allowBossMobsToBeInserted = false
	allowBossMobsToBeProcessed = false

[mob_catcher]
	allowBosses = false
	allowTamed = false
	allowNamed = true
	allowVillagers = false
	allowInventoryMobs = false
	consumeOnFailedCapture = false
	#When true, mobs that normally present a boss bar cannot be captured. Debug mode overrides this.
	disableMobsWithBossBars = false
